remote_theme: marella/jekyll-theme-documentation

permalink: pretty
baseurl: "/mscf-ml-postbacc"
title: "ML Postbacc Program"
description: "Machine Learning on HPC at the Morehouse Supercomputing Facility"

nav:
- Schedule:
  - Weeks 4-9 ML Training: ./Schedule/weeks-4-9
  - Weeks 10-12 Capstone: ./Schedule/weeks-10-12
- Machine Learning (Weeks 4-9):
  - Introduction to ML: ./02-ML/01-intro-to-ml
  - Supervised Learning: ./02-ML/02-supervised-learning
  - Unsupervised Learning: ./02-ML/03-unsupervised-learning
  - Evaluation and Optimization: ./02-ML/04-evaluation-optimization
  - Deep Learning: ./02-ML/05-deep-learning
  - Model Deployment: ./02-ML/06-deployment
- Capstone (Weeks 10-12):
  - Capstone Overview: ./03-Capstone/01-overview
  - Poster Requirements: ./03-Capstone/02-poster-requirements
